# Generated by Django 4.1.2 on 2022-10-20 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habituser',
            name='username',
            field=models.CharField(default='username', max_length=200),
        ),
        migrations.CreateModel(
            name='UserAndHabitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.datetime.now)),
                ('longest_steak', models.IntegerField()),
                ('total_steak', models.IntegerField()),
                ('current_steak', models.IntegerField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habituser')),
            ],
        ),
    ]
