# Generated by Django 4.1.2 on 2022-10-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habituser_username_userandhabitmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userandhabitmembership',
            name='current_steak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userandhabitmembership',
            name='longest_steak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userandhabitmembership',
            name='total_steak',
            field=models.IntegerField(default=0),
        ),
    ]
