# Generated by Django 4.1.2 on 2022-10-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_userandhabitmembership_current_steak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='members',
            field=models.ManyToManyField(through='habits.UserAndHabitMembership', to='habits.habituser'),
        ),
        migrations.CreateModel(
            name='UserAndHabitMembershipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField()),
                ('user_and_habit_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.userandhabitmembership')),
            ],
        ),
    ]
